---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx-latest
  template:
    metadata:
      labels:
       app: my-nginx-latest
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: my-nginx-latest
          image: "${TESTING_IMAGE}"
          imagePullPolicy: IfNotPresent